### ISSUE TITLE
debounce function

### ISSUE THREAD

**Issue by coot** [purescript-contrib/purescript-js-timers#5]
Would you accept a PR with a `debounce` function?

**Comment by garyb** [comment]
This library is just intended to provide FFI mappings to the JS API, so probably not - we could create a general `purescript-timers` library that is FFI-agnostic and provide it there perhaps. It seems `Aff`-y too maybe?

**Comment by coot** [comment]
`purescript-timers` seems like a good idea.  We probably need both `Eff` and `Aff` version.

**Comment by garyb** [comment]
I'm not sure exactly what the interface would look like for it - maybe just a class with, yeah, `Eff` and `Aff` instances and common timer-y functions. Explicit dictionary passing is also an option perhaps.

**Comment by coot** [comment]
In Eff I was thinking about something of this sort:
```
debounce
  :: forall e
   . Int
  -> (Eff (ref :: REF, timer :: TIMER | e) Unit)
  -> Eff (ref :: REF, timer :: TIMER | e) (Eff (ref :: REF, timer :: TIMER | e) Unit)
debounce i m = do
  ref <- newRef Nothing
  pure do
    _ <- runMaybeT do
      tid <- MaybeT (readRef ref)
      lift $ clearTimeout tid
    tid <- setTimeout i m
    writeRef ref (Just tid)
```

I think this can be lifted to `MonadEff`.

**Comment by thomashoneyman** [comment]
Closing this issue as we're not planning to add anything beyond FFI mappings to this repository.
